print('=====EXERCÍCIO 23=====')
n = str(input('Insira em número: ')).strip()
print('Analizando o número {}...'.format(n))
print('Unidade: {}'.format(n[3]))
print('Dezena: {}'.format(n[2]))
print('Centena: {}'.format(n[1]))
print('Milhar: {}'.format(n[0]))
